sudo: false
language: node_js
node_js:
- '8'
- '7'
before_script:
  - psql -c "create database objection_switch_test;" -U postgres
  - mysql -e "create database objection_switch_test;"
install:
  - yarn global add babel-cli
  - yarn global add coveralls
  - yarn install
after_success: yarn run coverage